name: "Test shield"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  board_3_1_0:
    uses: catie-aq/zephyr_workflows/.github/workflows/shield.yml@main
    with:
      shield: "zest_sensor_imu_3_1_0"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}

  board_4_0_0:
    uses: catie-aq/zephyr_workflows/.github/workflows/shield.yml@main
    with:
      shield: "zest_sensor_imu_4_0_0"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
